apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.castService.replicas }}
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
        - name: cast-service
          image: {{ .Values.castService.image }}:{{ .Values.castService.tag }}
          ports:
            - containerPort: {{ .Values.castService.port }}
          env:
            - name: DATABASE_URI
              value: "postgresql://{{ .Values.castDb.credentials.user }}:{{ .Values.castDb.credentials.password }}@cast-db:5432/{{ .Values.castDb.credentials.database }}"

---
apiVersion: v1
kind: Service
metadata:
  name: cast-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: cast-service
  ports:
    - port: {{ .Values.castService.port }}
      targetPort: {{ .Values.castService.port }}
  type: ClusterIP