apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cast-db-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.castDb.storage }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cast-db
  namespace: {{ .Values.namespace }}
spec:
  serviceName: cast-db
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.castDb.image }}
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: cast-db-secret
          volumeMounts:
            - name: cast-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: cast-db-storage
          persistentVolumeClaim:
            claimName: cast-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: cast-db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: cast-db
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None