apiVersion: v1
kind: Secret
metadata:
  name: movie-db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.movieDb.credentials.user }}
  POSTGRES_PASSWORD: {{ .Values.movieDb.credentials.password }}
  POSTGRES_DB: {{ .Values.movieDb.credentials.database }}

---
apiVersion: v1
kind: Secret
metadata:
  name: cast-db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.castDb.credentials.user }}
  POSTGRES_PASSWORD: {{ .Values.castDb.credentials.password }}
  POSTGRES_DB: {{ .Values.castDb.credentials.database }}