apiVersion: v1
kind: Secret
metadata:
  name: movie-db-secret
  namespace: prod
type: Opaque
data:
  POSTGRES_USER: bW92aWVfZGJfdXNlcm5hbWU=
  POSTGRES_PASSWORD: bW92aWVfZGJfcGFzc3dvcmQ=
  POSTGRES_DB: bW92aWVfZGJfZGV2
---
apiVersion: v1
kind: Secret
metadata:
  name: cast-db-secret
  namespace: prod
type: Opaque
data:
  POSTGRES_USER: Y2FzdF9kYl91c2VybmFtZQ==
  POSTGRES_PASSWORD: Y2FzdF9kYl9wYXNzd29yZA==
  POSTGRES_DB: bW92aWVfZGJfZGV2